### PR TITLE
[OSSM-6738] MTT:  GatewayAPI is enabled by default in ClusterWide mode

### PR DESCRIPTION
**Pull request by unsortedhashsets**
1. Added to TestClusterWideMode gateway API default state test (ClusterWide)
2. Added to TestGatewayApi gateway API default state test  (MultiTenant)
3. Added to TestClusterWideMode testcase Deploy_the_Kubernetes_Gateway_API from TestGatewayApi to test not only  on MultiTenant but also on ClusterWide

**SMCP_VERSION=2.5 TEST_CASE=TestClusterWideMode:**
```
=== RUN   TestClusterWideMode/check_Gateway_API_settings
    clusterwide_mode_test.go:67: Check Gateway API is disabled by default
    clusterwide_mode_test.go:69: Related issue: https://issues.redhat.com/browse/OSSM-6693
    clusterwide_mode_test.go:71:    
    clusterwide_mode_test.go:71: STEP 1: Check istiod deployment environment variables
    clusterwide_mode_test.go:88:    Env PILOT_ENABLE_GATEWAY_API is set to false
    clusterwide_mode_test.go:88:    Env PILOT_ENABLE_GATEWAY_API_STATUS is set to false
    clusterwide_mode_test.go:88:    Env PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER is set to false
    subtest.go:25: 
    subtest.go:32: Subtest completed in 0.68s (excluding cleanup)
=== RUN   TestClusterWideMode/Deploy_the_Kubernetes_Gateway_API_in_ClusterWide_mode
    clusterwide_mode_test.go:110:    
    clusterwide_mode_test.go:110: STEP 1: Install httpbin
    clusterwide_mode_test.go:111:    Install app "httpbin" in namespace "foo"
    clusterwide_mode_test.go:111:    Wait for app foo/httpbin to be ready
    clusterwide_mode_test.go:114:    
    clusterwide_mode_test.go:114: STEP 2: Enable the Gateway for SMCP < 2.6
    clusterwide_mode_test.go:127:    
    clusterwide_mode_test.go:127: STEP 3: Deploy the Gateway API configuration including a single exposed route (i.e., /get)
    clusterwide_mode_test.go:133:    
    clusterwide_mode_test.go:133: STEP 4: Wait for Gateway to be ready
    clusterwide_mode_test.go:134:    Wait for condition condition=Programmed on Gateway foo/gateway...
    clusterwide_mode_test.go:134:    SUCCESS: Condition condition=Programmed met by Gateway foo/gateway
    clusterwide_mode_test.go:136:    
    clusterwide_mode_test.go:136: STEP 5: Verfiy the GatewayApi access the httpbin service using curl
    clusterwide_mode_test.go:138:    SUCCESS: Access the httpbin service with GatewayApi
    subtest.go:25: 
    subtest.go:32: Subtest completed in 10.11s (excluding cleanup)
```

**SMCP_VERSION=2.5 TEST_CASE=TestGatewayApi:**
```
== RUN   TestGatewayApi/Check_default_Gateway_API_settings
    gatewayapi_test.go:44: Check Gateway API is disabled by default
    gatewayapi_test.go:46:    
    gatewayapi_test.go:46: STEP 1: Check istiod deployment environment variables
    gatewayapi_test.go:63:    Env PILOT_ENABLE_GATEWAY_API is set to false
    gatewayapi_test.go:63:    Env PILOT_ENABLE_GATEWAY_API_STATUS is set to false
    gatewayapi_test.go:63:    Env PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER is set to false
    subtest.go:25: 
    subtest.go:32: Subtest completed in 1.15s (excluding cleanup)
```

**SMCP_VERSION=2.6 TEST_CASE=TestClusterWideMode:**
```
=== RUN   TestClusterWideMode/check_Gateway_API_settings
    clusterwide_mode_test.go:65: Check Gateway API is enabled by default for SMCP >= 2.6
    clusterwide_mode_test.go:69: Related issue: https://issues.redhat.com/browse/OSSM-6693
    clusterwide_mode_test.go:71:    
    clusterwide_mode_test.go:71: STEP 1: Check istiod deployment environment variables
    clusterwide_mode_test.go:100:    All variables were checked, PILOT_ENABLE_GATEWAY_API variables were not detected
    subtest.go:25: 
    subtest.go:32: Subtest completed in 1.00s (excluding cleanup)
=== RUN   TestClusterWideMode/Deploy_the_Kubernetes_Gateway_API_in_ClusterWide_mode
    clusterwide_mode_test.go:110:    
    clusterwide_mode_test.go:110: STEP 1: Install httpbin
    clusterwide_mode_test.go:111:    Install app "httpbin" in namespace "foo"
    clusterwide_mode_test.go:111:    Wait for app foo/httpbin to be ready
    clusterwide_mode_test.go:127:    
    clusterwide_mode_test.go:127: STEP 2: Deploy the Gateway API configuration including a single exposed route (i.e., /get)
    clusterwide_mode_test.go:133:    
    clusterwide_mode_test.go:133: STEP 3: Wait for Gateway to be ready
    clusterwide_mode_test.go:134:    Wait for condition condition=Programmed on Gateway foo/gateway...
    clusterwide_mode_test.go:134:    SUCCESS: Condition condition=Programmed met by Gateway foo/gateway
    clusterwide_mode_test.go:136:    
    clusterwide_mode_test.go:136: STEP 4: Verfiy the GatewayApi access the httpbin service using curl
    clusterwide_mode_test.go:138:    SUCCESS: Access the httpbin service with GatewayApi
    subtest.go:25: 
    subtest.go:32: Subtest completed in 11.15s (excluding cleanup)
```

**SMCP_VERSION=2.6 TEST_CASE=TestGatewayApi:** 
```
=== RUN   TestGatewayApi/Check_default_Gateway_API_settings
    gatewayapi_test.go:44: Check Gateway API is disabled by default
    gatewayapi_test.go:46:    
    gatewayapi_test.go:46: STEP 1: Check istiod deployment environment variables
    gatewayapi_test.go:63:    Env PILOT_ENABLE_GATEWAY_API is set to false
    gatewayapi_test.go:63:    Env PILOT_ENABLE_GATEWAY_API_STATUS is set to false
    gatewayapi_test.go:63:    Env PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER is set to false
    subtest.go:25: 
    subtest.go:32: Subtest completed in 0.70s (excluding cleanup)
```

Related:

- https://issues.redhat.com/browse/OSSM-6738
- https://issues.redhat.com/browse/OSSM-6693

### CODE REVIEW

**Comment by mkralik3** [comment]
@unsortedhashsets 
Can you please add another test to check that it is still disabled when cluster mode is `MultiTenant` in SMCP 2.6? 
Also, can you please add new section into GatewayAPI test to not use 
```
spec:
          techPreview:
            gatewayAPI:
              enabled: true
``` 
anymore for SMCP 2.6? (e.g. update the IF there)

**Comment by unsortedhashsets** [comment]
> @unsortedhashsets Can you please add another test to check that it is still disabled when cluster mode is `MultiTenant` in SMCP 2.6? Also, can you please add new section into GatewayAPI test to not use
> 
> ```
> spec:
>           techPreview:
>             gatewayAPI:
>               enabled: true
> ```
> 
> anymore for SMCP 2.6? (e.g. update the IF there)

Hi @mkralik3 , from my point of view, there is not change in 2.6 vs 2.5 GatewayAPI for MultiTenant (as it now enabled only for ClusterWide by default). 
For the successful GatewayAPI test there is still needed the same spec as for 2.5 (I tried to skip it for 2.6 :smile:)
So changes only related to ClusterWide behaviour

**Comment by mkralik3** [comment]
@unsortedhashsets yes, the behavior has not changed but we have never tested it before for `MultiTenant` so it would be fine to have it there :) 

ah right, the GatewayApi test doesn't have an explicitly selected mode in SMCP, so, it is MultiTenant by default :(  so that is probably why GatewayApi test didn't pass. You can add new test case for 2.6 only to run that in clusterwide mode ( but it would probably require to refactor that test a little, to generalize the checking section etc. )

**Comment by mkralik3** [comment]
```
    --- FAIL: TestClusterWideMode/Deploy_the_Kubernetes_Gateway_API_in_ClusterWide_mode (20.22s)
```
This test fails on 2.5.2 operator with 2.5 smcp .

The clusterwide test doesn't install Install Gateway API CRD's so that is probably why it is failing. ,MTT test doesn't expect that Gateway API CRD's  are installed on the cluster as Kiali jobs ( and they should clean them up after the tests, same as in Gateway API test )

**Review by mkralik3 — CHANGES_REQUESTED** [review]
```
    --- FAIL: TestClusterWideMode/Deploy_the_Kubernetes_Gateway_API_in_ClusterWide_mode (20.22s)
```
This test fails on 2.5.2 operator with 2.5 smcp .

The clusterwide test doesn't install Install Gateway API CRD's so that is probably why it is failing. ,MTT test doesn't expect that Gateway API CRD's  are installed on the cluster as Kiali jobs ( and they should clean them up after the tests, same as in Gateway API test )

**Comment by unsortedhashsets** [comment]
> ```
>     --- FAIL: TestClusterWideMode/Deploy_the_Kubernetes_Gateway_API_in_ClusterWide_mode (20.22s)
> ```
> 
> This test fails on 2.5.2 operator with 2.5 smcp .
> 
> The clusterwide test doesn't install Install Gateway API CRD's so that is probably why it is failing. ,MTT test doesn't expect that Gateway API CRD's are installed on the cluster as Kiali jobs ( and they should clean them up after the tests, same as in Gateway API test )

Yep, thanks, seems same issue you pointed here https://github.com/maistra/maistra-test-tool/pull/701
As 2.5 operator did not support by default gateway API in cluster mode, will update the condition to install/clean CRD in <2.6.0 in clustermode, and will test also with 2.5.2 operator

**Comment by mkralik3** [comment]
@unsortedhashsets neither 2.5 nor 2.6 operator should not install GatewayAPI CRD's if I understand that correctly. In each version, it is user responsibility to have GatewayAPI CRD's installed.
Or, does 2.6 operator install Gateway API CRD's ?

**Comment by unsortedhashsets** [comment]
> @unsortedhashsets neither 2.5 nor 2.6 operator should not install GatewayAPI CRD's if I understand that correctly. In each version, it is user responsibility to have GatewayAPI CRD's installed. Or, does 2.6 operator install Gateway API CRD's ?

Oh yep, I misunderstood, got it!

**Comment by unsortedhashsets** [comment]
> @unsortedhashsets neither 2.5 nor 2.6 operator should not install GatewayAPI CRD's if I understand that correctly. In each version, it is user responsibility to have GatewayAPI CRD's installed. Or, does 2.6 operator install Gateway API CRD's ?

- Added CRD install/clean up where needed
- Found out some problem with ClusterWide mode + Gateway API in SMCP 2.4 for both operators 2.5.2 / 2.6.0 -> https://issues.redhat.com/browse/OSSM-6765 (skip test for 2.4 now to unblock other scenarios)

Tests passed for 2.5.2 and 2.6.0 all SMCPs (except skipped 2.4)

**Review by mkralik3 — APPROVED** [review]

**Pull request merged**
