### PR TITLE
Add info on how to run/debug a test via VSCode

### PR DESCRIPTION
**Pull request by mkralik3**

### CODE REVIEW

**Comment by mkralik3** [comment]
Also, the predefined `launch.json` can be added directly into the repository (/.vscode/launch.json) instead of being mentioned in Readme but I don't know if we want to have IDE specific file directly in the repo, so, I only mentioned it in the Readme.

**Comment by fjglira** [comment]
Look great for me. Really nice to have that explanation on the read me file

**Review by fjglira — APPROVED** [review]
lgtm

**Comment by mkralik3** [comment]
@fjglira sorry, I totally missed the notification from this pr. 
I noticed that some jobs are still waiting. Do I need to add `openshift-ci` bot into my fork repo in order to move this forward?

**Comment by fjglira** [comment]
Hi @mkralik3 , sorry for the delayed answer. Checking if I can add you to the organization

**Comment by fjglira** [comment]
I can't add you as member of the QE team (I do not have the privileges) but I added you as a mantainer. Please take a look

**Pull request merged**
